insert into configuracion (id_configuracion,
                            artilleria_cantidad,artilleria_danio,artilleria_radio_disparo,artilleria_salud,
                            avion_combustible,avion_danio,avion_radio_vision,avion_salud,avion_velocidad,
                            bomba_danio,bomba_radio_impacto,
                            campo_tamaniox,campo_tamanioy,
                            base_tamaniox,base_tamanioy,
                            deposito_explosivos_salud,
                            mapa_tamaniox,mapa_tamanioy,
                            tanque_combustible_salud,
                            torre_danio,torre_radio_disparo,torre_salud)
                            values (1, 
                            8, 10, 450, 50, 
                            85,30,35,80,150,
                            25,26,
                            300,400,
                            156,103,
                            70,
                            1446,996,
                            70,
                            20,60,90);